/**
 * Agent Scaffold Writer
 *
 * Writes the agent context directory (.trellis/agents/) during `trellis init`.
 * Produces AGENTS.md (human + AI readable), agent-context.json (machine
 * readable), and stub directories for skills and workflows.
 *
 * The agent config is named `agent-context.json` (not `config.json`) to avoid
 * collision with `.trellis/config.json` which stores engine configuration.
 *
 * @module trellis/scaffold/write
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import type { ProjectContext } from './infer.js';
import type { UserProfile } from './profile.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AgentScaffoldConfig {
  domain: string | null;
  ecosystem: string | null;
  tools: string[];
  ontologies: string[];
  generatedAt: string;
  confidence: string;
}

export interface ScaffoldInput {
  profile: UserProfile | null;
  context: ProjectContext;
}

export type IdeType = 'cursor' | 'windsurf' | 'claude' | 'copilot' | 'codex' | 'gemini' | 'none';
export type WorkspaceFootprint = 'minimal' | 'standard' | 'full';
export type FrameworkType = 'react' | 'vue' | 'svelte' | 'next' | 'nuxt' | 'remotion' | 'expo' | 'bun' | 'node' | 'cli' | 'library' | 'animation' | 'games' | 'none';

export interface IdeScaffoldInput {
  ide: IdeType;
  footprint: WorkspaceFootprint;
  framework: FrameworkType;
  plugins: string[];
  rootPath: string;
  context: ProjectContext;
  profile: UserProfile | null;
}

// ---------------------------------------------------------------------------
// Template renderers
// ---------------------------------------------------------------------------

function renderAgentsMd(
  profile: UserProfile | null,
  context: ProjectContext,
): string {
  const userName = profile?.name ?? 'the user';
  const userBio =
    profile?.bio ||
    '(No bio provided — run `trellis season` to set up your profile.)';
  const userSkills = profile?.skills?.length
    ? profile.skills.join(', ')
    : '(not specified)';
  const userStyle = profile?.style || '(not specified)';
  const userVerbosity = profile?.preferences?.verbosity ?? 'balanced';
  const userTone = profile?.preferences?.tone ?? 'peer';

  const projectName = context.name ?? '(unnamed)';
  const projectDomain =
    context.domain ??
    '(not determined — run `trellis season` to specify)';
  const projectDesc = context.description ?? '(no description found)';
  const projectEco = context.ecosystem ?? 'unknown';
  const confidence = context.confidence;

  return `# Trellis Agent Context

> This file was generated by \`trellis init\` and should be kept up to date.
> Inference confidence: **${confidence}**

---

## About the User

| Field | Value |
|-------|-------|
| **Name** | ${userName} |
| **Bio** | ${userBio} |
| **Skills** | ${userSkills} |
| **Style** | ${userStyle} |
| **Preferred verbosity** | ${userVerbosity} |
| **Preferred tone** | ${userTone} |

---

## About This Project

| Field | Value |
|-------|-------|
| **Name** | ${projectName} |
| **Domain** | ${projectDomain} |
| **Description** | ${projectDesc} |
| **Ecosystem** | ${projectEco} |
| **File count** | ~${context.fileCount} |

---

## Agent Instructions

You are operating in a Trellis-tracked repository. Follow these guidelines:

1. **Read \`agent-context.json\`** in this directory for registered tools, ontologies, and domain settings.
2. **Check \`skills/\`** for domain-specific operating instructions relevant to this project.
3. **Check \`workflows/\`** for repeatable task procedures. Favor existing workflows before improvising.
4. **Update this file** as the project evolves — new teammates, new goals, new tools.
5. **Communicate through Trellis** — prefer writing to the graph kernel over mutating files directly when recording decisions or state.
6. **Run \`trellis season\`** if context seems incomplete or out of date.

---

## Quick Reference

\`\`\`bash
trellis status          # Current repo state
trellis log             # Causal operation history
trellis milestone       # Create narrative checkpoints
trellis ask "..."       # Semantic search across the repo
trellis season          # Re-run domain onboarding
\`\`\`
`;
}

function renderConfigJson(context: ProjectContext): AgentScaffoldConfig {
  return {
    domain: context.domain,
    ecosystem: context.ecosystem,
    tools: [],
    ontologies: [],
    generatedAt: new Date().toISOString(),
    confidence: context.confidence,
  };
}

function renderSkillsReadme(): string {
  return `# Skills

Place domain-specific operating instructions here as \`.md\` files.

Each skill file should follow the format:

\`\`\`markdown
---
name: Skill Name
description: When to use this skill.
---

# Instructions
...
\`\`\`

The agent will discover and read skill files relevant to the current task.
`;
}

function renderWorkflowsReadme(): string {
  return `# Workflows

Place repeatable task procedures here as \`.md\` files.

Each workflow file should follow the format:

\`\`\`markdown
---
description: Short description of what this workflow does.
---

## Steps

1. Step one
2. Step two
// turbo
3. Auto-runnable step
\`\`\`

Add \`// turbo\` above a step to allow the agent to auto-run it without confirmation.
Add \`// turbo-all\` anywhere in the file to auto-run every step.
`;
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Write the full agent scaffold into .trellis/agents/.
 *
 * @param rootPath - Absolute path to the repository root
 * @param input    - Profile and inferred project context
 */
export function writeAgentScaffold(
  rootPath: string,
  input: ScaffoldInput,
): void {
  const agentsDir = join(rootPath, '.trellis', 'agents');
  const skillsDir = join(agentsDir, 'skills');
  const workflowsDir = join(agentsDir, 'workflows');

  // Create directories
  for (const dir of [agentsDir, skillsDir, workflowsDir]) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
  }

  // AGENTS.md — always write (overwrite to stay fresh on re-init)
  writeFileSync(
    join(agentsDir, 'AGENTS.md'),
    renderAgentsMd(input.profile, input.context),
    'utf-8',
  );

  // agent-context.json — always write
  writeFileSync(
    join(agentsDir, 'agent-context.json'),
    JSON.stringify(renderConfigJson(input.context), null, 2),
    'utf-8',
  );

  // Stub READMEs — only if directory is empty
  const skillsReadmePath = join(skillsDir, 'README.md');
  if (!existsSync(skillsReadmePath)) {
    writeFileSync(skillsReadmePath, renderSkillsReadme(), 'utf-8');
  }

  const workflowsReadmePath = join(workflowsDir, 'README.md');
  if (!existsSync(workflowsReadmePath)) {
    writeFileSync(workflowsReadmePath, renderWorkflowsReadme(), 'utf-8');
  }
}

// ---------------------------------------------------------------------------
// IDE-specific scaffold writers
// ---------------------------------------------------------------------------

function renderCursorRules(
  input: IdeScaffoldInput,
): string {
  const projectName = input.context.name ?? 'this project';
  const domain = input.context.domain ?? 'general';
  const eco = input.context.ecosystem ?? 'unknown';
  const framework = input.framework && input.framework !== 'none' ? input.framework : 'vanilla';
  const plugins = input.plugins.length > 0
    ? input.plugins.map(p => `- ${p}`).join('\n')
    : '(none selected)';

  return `# Cursor Rules for ${projectName}

> Generated by \`trellis init\`

## Project Context
- **Domain**: ${domain}
- **Framework**: ${framework}
- **Ecosystem**: ${eco}
- **Confidence**: ${input.context.confidence}

## Selected Features
${plugins}

## Agent Instructions
You are working in a Trellis-tracked repository. See \`.trellis/agents/AGENTS.md\` for full context.

## Commands
- \`trellis status\` — Check repo state
- \`trellis seed\` — Refresh this context file
- \`trellis log\` — View causal history

---
*Auto-generated by Trellis. Run \`trellis seed\` to refresh context.*
`;
}

function renderWindsurfRules(
  input: IdeScaffoldInput,
): string {
  const projectName = input.context.name ?? 'this project';
  const domain = input.context.domain ?? 'general';
  const eco = input.context.ecosystem ?? 'unknown';
  const framework = input.framework && input.framework !== 'none' ? input.framework : 'vanilla';
  const plugins = input.plugins.length > 0
    ? input.plugins.map(p => `- ${p}`).join('\n')
    : '(none selected)';

  return `# Windsurf Rules for ${projectName}

> Generated by \`trellis init\`

## Project Context
- **Domain**: ${domain}
- **Framework**: ${framework}
- **Ecosystem**: ${eco}
- **Confidence**: ${input.context.confidence}

## Selected Features
${plugins}

## Agent Instructions
You are working in a Trellis-tracked repository. See \`.trellis/agents/AGENTS.md\` for full context.

## Commands
- \`trellis status\` — Check repo state
- \`trellis seed\` — Refresh this context file
- \`trellis log\` — View causal history

---
*Auto-generated by Trellis. Run \`trellis seed\` to refresh context.*
`;
}

function renderClaudeMd(
  input: IdeScaffoldInput,
): string {
  const projectName = input.context.name ?? 'this project';
  const domain = input.context.domain ?? 'general';
  const eco = input.context.ecosystem ?? 'unknown';
  const framework = input.framework && input.framework !== 'none' ? input.framework : 'vanilla';
  const plugins = input.plugins.length > 0
    ? input.plugins.map(p => `- ${p}`).join('\n')
    : '(none selected)';

  return `# Claude Context for ${projectName}

> Generated by \`trellis init\`

## Project Context
- **Domain**: ${domain}
- **Framework**: ${framework}
- **Ecosystem**: ${eco}
- **Confidence**: ${input.context.confidence}

## Selected Features
${plugins}

## Agent Instructions
You are working in a Trellis-tracked repository. See \`.trellis/agents/AGENTS.md\` for full context.

## Commands
- \`trellis status\` — Check repo state
- \`trellis seed\` — Refresh this context file
- \`trellis log\` — View causal history

---
*Auto-generated by Trellis. Run \`trellis seed\` to refresh context.*
`;
}

function renderCopilotConfig(
  input: IdeScaffoldInput,
): Record<string, unknown> {
  return {
    version: '1.0',
    generatedBy: 'trellis init',
    context: {
      domain: input.context.domain,
      framework: input.framework,
      ecosystem: input.context.ecosystem,
      projectName: input.context.name,
      confidence: input.context.confidence,
    },
    plugins: input.plugins,
  };
}

function renderCodexConfig(
  input: IdeScaffoldInput,
): Record<string, unknown> {
  return {
    version: '1.0',
    generatedBy: 'trellis init',
    context: {
      domain: input.context.domain,
      framework: input.framework,
      ecosystem: input.context.ecosystem,
      projectName: input.context.name,
      confidence: input.context.confidence,
    },
    features: input.plugins,
  };
}

function renderGeminiConfig(
  input: IdeScaffoldInput,
): Record<string, unknown> {
  return {
    version: '1.0',
    generatedBy: 'trellis init',
    context: {
      domain: input.context.domain,
      framework: input.framework,
      ecosystem: input.context.ecosystem,
      projectName: input.context.name,
      confidence: input.context.confidence,
    },
    features: input.plugins,
  };
}

/**
 * Write IDE-specific dotfolder scaffolds.
 *
 * @param rootPath - Absolute path to the repository root
 * @param input    - IDE type, footprint, plugins, context, and profile
 */
export function writeIdeScaffold(
  rootPath: string,
  input: IdeScaffoldInput,
): void {
  const { ide, footprint, framework, plugins, context, profile } = input;
  const fullInput: IdeScaffoldInput = {
    ide,
    footprint,
    framework,
    plugins,
    rootPath,
    context,
    profile,
  };

  switch (ide) {
    case 'cursor': {
      const cursorDir = join(rootPath, '.cursor');
      if (!existsSync(cursorDir)) {
        mkdirSync(cursorDir, { recursive: true });
      }
      writeFileSync(
        join(cursorDir, 'rules.md'),
        renderCursorRules(fullInput),
        'utf-8',
      );
      break;
    }

    case 'windsurf': {
      const windsurfDir = join(rootPath, '.windsurf');
      if (!existsSync(windsurfDir)) {
        mkdirSync(windsurfDir, { recursive: true });
      }
      writeFileSync(
        join(windsurfDir, 'rules.md'),
        renderWindsurfRules(fullInput),
        'utf-8',
      );
      break;
    }

    case 'claude': {
      const claudeDir = join(rootPath, '.claude');
      if (!existsSync(claudeDir)) {
        mkdirSync(claudeDir, { recursive: true });
      }
      writeFileSync(
        join(claudeDir, 'settings.md'),
        renderClaudeMd(fullInput),
        'utf-8',
      );
      break;
    }

    case 'copilot': {
      const copilotDir = join(rootPath, '.github');
      const copilotDirSub = join(copilotDir, 'copilot');
      if (!existsSync(copilotDirSub)) {
        mkdirSync(copilotDirSub, { recursive: true });
      }
      writeFileSync(
        join(copilotDirSub, 'config.json'),
        JSON.stringify(renderCopilotConfig(fullInput), null, 2),
        'utf-8',
      );
      break;
    }

    case 'codex': {
      const codexDir = join(rootPath, '.codex');
      if (!existsSync(codexDir)) {
        mkdirSync(codexDir, { recursive: true });
      }
      writeFileSync(
        join(codexDir, 'config.json'),
        JSON.stringify(renderCodexConfig(fullInput), null, 2),
        'utf-8',
      );
      break;
    }

    case 'gemini': {
      const geminiDir = join(rootPath, '.gemini');
      if (!existsSync(geminiDir)) {
        mkdirSync(geminiDir, { recursive: true });
      }
      writeFileSync(
        join(geminiDir, 'config.json'),
        JSON.stringify(renderGeminiConfig(fullInput), null, 2),
        'utf-8',
      );
      break;
    }

    case 'none':
      break;
  }

  if (footprint === 'full') {
    const agentsDir = join(rootPath, '.trellis', 'agents');
    if (existsSync(agentsDir)) {
      const current = readFileSync(join(agentsDir, 'AGENTS.md'), 'utf-8');
      const updated = current.replace(
        /## Quick Reference[\s\S]*$/,
        `## Quick Reference

\`\`\`bash
trellis status          # Current repo state
trellis log             # Causal operation history
trellis seed            # Refresh agent context (${ide})
trellis milestone       # Create narrative checkpoints
\`\`\`
`,
      );
      writeFileSync(join(agentsDir, 'AGENTS.md'), updated, 'utf-8');
    }
  }
}
