packages:
  - "."
  - "demo/*"
allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  onnxruntime-node: set this to true or false
  opencode-ai: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - turtlecode-backend-darwin-arm64@0.3.71
  - turtlecode-backend-darwin-x64-baseline@0.3.71
  - turtlecode-backend-darwin-x64@0.3.71
  - turtlecode-backend-linux-arm64-musl@0.3.71
  - turtlecode-backend-linux-arm64@0.3.71
  - turtlecode-backend-linux-x64-baseline-musl@0.3.71
  - turtlecode-backend-linux-x64-baseline@0.3.71
  - turtlecode-backend-linux-x64-musl@0.3.71
  - turtlecode-backend-linux-x64@0.3.71
  - turtlecode-backend-windows-arm64@0.3.71
  - turtlecode-backend-windows-x64-baseline@0.3.71
  - turtlecode-backend-windows-x64@0.3.71
  - turtlecode@0.3.71
