#!/usr/bin/env node
/**
 * Generate docs/INDEX.md, llms.txt "Primary documents" section, and
 * docs/devlog/README.md from git-tracked docs frontmatter.
 *
 *   node scripts/docs-index.mjs
 *
 * Deterministic: path-sorted, idempotent. Reads frontmatter (fallback: first
 * heading) for all git-tracked docs/*.md and docs/ subdirectory md files.
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const LLMS_START = '<!-- docs-index:start -->';
const LLMS_END = '<!-- docs-index:end -->';
const DEVLOG_DIR = path.join(ROOT, 'docs/devlog');

function gitFiles() {
  const out = execSync('git ls-files "docs/*.md" "docs/**/*.md"', {
    cwd: ROOT,
    encoding: 'utf8',
  });
  return out
    .split('\n')
    .map((s) => s.trim())
    .filter(Boolean);
}

function devlogFiles() {
  try {
    return readdirSync(DEVLOG_DIR)
      .filter((f) => f.endsWith('.md') && f !== 'README.md')
      .sort()
      .map((f) => `docs/devlog/${f}`);
  } catch {
    return [];
  }
}

function readDoc(file) {
  const src = readFileSync(path.join(ROOT, file), 'utf8');
  const data = {};
  let body = src;
  if (src.startsWith('---\n')) {
    const end = src.indexOf('\n---\n', 4);
    if (end !== -1) {
      const fm = src.slice(4, end);
      for (const line of fm.split('\n')) {
        const m = line.match(/^([a-zA-Z-]+):\s*(.*)$/);
        if (m) data[m[1]] = m[2].trim();
      }
      body = src.slice(end + 5);
    }
  }
  const title =
    data.title || (body.match(/^#\s+(.+)$/m) || [])[1]?.trim() || path.basename(file, '.md');
  const desc = data.description || '';
  const status = data.status || 'draft';
  return { file, title, desc, status, devlog: data.date ? data : null };
}

function isDevlog(file) {
  return file.startsWith('docs/devlog/');
}

function genreOf(file) {
  const rel = file.replace(/^docs\//, '');
  const parts = rel.split('/');
  if (parts.length === 1) return 'Top-level';
  const g = parts[0];
  const map = {
    adr: 'Architecture Decision Records',
    specs: 'Specs',
    planning: 'Planning',
    'trellis-ui': 'Trellis UI',
    applications: 'Applications',
    essays: 'Essays',
    artifacts: 'Design Artifacts',
    devlog: 'Devlog',
  };
  return map[g] || parts[0];
}

function renderIndex(all) {
  const genres = new Map();
  for (const d of all) {
    const g = genreOf(d.file);
    if (!genres.has(g)) genres.set(g, []);
    genres.get(g).push(d);
  }
  const sorted = [...genres.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  const active = [];
  const archived = [];
  for (const [genre, docs] of sorted) {
    const lines = [`## ${genre}`, '', '| Title | Status | Path |', '| ----- | ------ | ---- |'];
    for (const d of [...docs].sort((a, b) => a.file.localeCompare(b.file))) {
      if (d.status === 'archived') {
        archived.push(`- **${d.title}** — ${d.file}`);
        continue;
      }
      const link = d.file.replace(/^docs\//, '');
      lines.push(`| ${d.title} | ${d.status} | [${link}](./${link}) |`);
    }
    active.push(lines.join('\n'));
  }
  const body = [
    '# Trellis Docs Index',
    '',
    '> Generated by `node scripts/docs-index.mjs` — do not edit by hand.',
    '> Contract: [`docs/FRONTMATTER.md`](./FRONTMATTER.md)',
    '',
    ...active,
  ];
  if (archived.length) {
    body.push('', '## Archived', '', ...archived.sort());
  }
  return `${body.join('\n')}\n`;
}

function renderLlms(all) {
  const docs = all
    .filter((d) => d.status !== 'archived' && !isDevlog(d.file))
    .sort((a, b) => a.file.localeCompare(b.file));
  const lines = docs.map((d) => {
    const rel = d.file.replace(/^docs\//, '');
    const link = d.file.startsWith('docs/') ? `./${rel}` : `./${d.file}`;
    const label = d.title.startsWith('docs/') ? path.basename(d.file, '.md') : d.title;
    return `- [${label}](${link}): ${d.desc}`;
  });
  return [`${LLMS_START}`, ...lines, LLMS_END].join('\n');
}

function renderDevlog(devlogs) {
  const sorted = [...devlogs].sort((a, b) => (a.file > b.file ? -1 : 1));
  const rows = sorted.map((d) => {
    const date = d.devlog.date || '';
    const slug = path.basename(d.file, '.md');
    const link = `./${slug}.md`;
    return `| ${date} | [${d.title}](${link}) | ${d.devlog.arc || ''} | ${d.devlog.landed || ''} | ${d.devlog.next || ''} |`;
  });
  return [
    '# Devlog',
    '',
    '> Generated by `node scripts/docs-index.mjs` — do not edit by hand.',
    '',
    '| Date | Title | Arc | Landed | Next |',
    '| ---- | ----- | --- | ------ | ---- |',
    ...rows,
    '',
  ].join('\n');
}

const all = gitFiles().map(readDoc);
const docs = all.filter((d) => !isDevlog(d.file));
const devlogs = [...all.filter((d) => isDevlog(d.file)), ...devlogFiles().map(readDoc)];

writeFileSync(path.join(ROOT, 'docs/INDEX.md'), renderIndex(docs));

const llmsPath = path.join(ROOT, 'llms.txt');
const llmsSrc = readFileSync(llmsPath, 'utf8');
if (!llmsSrc.includes(LLMS_START) || !llmsSrc.includes(LLMS_END)) {
  throw new Error('llms.txt missing docs-index markers. Add them around "## Primary documents".');
}
const before = llmsSrc.slice(0, llmsSrc.indexOf(LLMS_START));
const after = llmsSrc.slice(llmsSrc.indexOf(LLMS_END) + LLMS_END.length);
writeFileSync(llmsPath, `${before}${renderLlms(docs)}${after}`);

if (devlogs.length) {
  mkdirSync(path.join(ROOT, 'docs/devlog'), { recursive: true });
  writeFileSync(path.join(ROOT, 'docs/devlog/README.md'), renderDevlog(devlogs));
}

console.log('✓ docs/INDEX.md regenerated');
console.log('✓ llms.txt "Primary documents" regenerated');
if (devlogs.length) console.log(`✓ docs/devlog/README.md regenerated (${devlogs.length} entries)`);
